### ISSUE TITLE
A php 7 fix

### ISSUE THREAD

**Issue by pcwalden** [tswaehn/phpmp#2]
cleanSort throws exception on utils.php line 18.

before 

utils.php line 8: $new_sort_array = "";

should be

$new_sort_array = [];

**Comment by tswaehn** [comment]
@pcwalden its merged. as you opened it, you may want to check/test and close - or you want me to close :) -- up to you

**Comment by pcwalden** [comment]
Tested with fetch from your repository. Working!

Thanks.
